Algoritmo "Olá Mundo"
// Disciplina  : [Lógica de Programação]
// Professor   : 
// Descrição   : Escreva um programa que mostre na tela a
//               mensagem "Olá, Mundo!"
// Autor(a)    : Filipe Azoubel
// Data atual  : 06/07/2022
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval()
escreval("Olá, mundo!")
escreval()

Fimalgoritmo